name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build & Push Frontend
      run: |
        docker build -t shiv201/frontend:latest ./frontend
        docker push shiv201/frontend:latest

    - name: Build & Push Backend
      run: |
        docker build -t shiv201/backend:latest ./backend
        docker push shiv201/backend:latest

    - name: Deploy to Kubernetes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          kubectl apply -f /path/to/k8s/ --namespace=amrutam

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "🚀 Deployed latest build to Kubernetes"
